name:                frontend
version:             1.0.0.0
github:              "jappeace/awesome-project-name"
license:             MIT
author:              "Jappie Klooster"
maintainer:          "jappieklooster@hotmail.com"
copyright:           "2018 Jappie Klooster"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/awesome-project-name#readme>

ghc-options: -Werror -Wall -Wcompat -Wincomplete-uni-patterns -Widentities  -Wno-simplifiable-class-constraints
ghcjs-options: -dedupe
cpp-options: -DGHCJS_BROWSER

dependencies:
- base >= 4.7 && < 5
- servant
- servant-reflex
- aeson # json
- text
- reflex-dom
- reflex
- containers
- common

library:
  source-dirs: src

executables:
  webservice:
    main:                frontend.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frontend

tests:
  awesome-project-name-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frontend
