name:                frontend
version:             0.1.0.0
github:              "githubuser/awesome-project-name"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/awesome-project-name#readme>

dependencies:
- base >= 4.7 && < 5
- servant-client # http server
- aeson # json
- bytestring
- text
- reflex-dom
- reflex
- containers
- common


library:
  source-dirs: src

executables:
  webservice:
    main:                frontend.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frontend

tests:
  awesome-project-name-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frontend
